# Generated by Django 4.2.7 on 2025-09-30 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current Account'), ('SAVINGS', 'Savings Account'), ('CASH_CREDIT', 'Cash Credit'), ('OVERDRAFT', 'Overdraft')], max_length=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='outlets.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('description', models.TextField()),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Card')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.expensecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='outlets.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('INFLOW', 'Cash Inflow'), ('OUTFLOW', 'Cash Outflow')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('reference_type', models.CharField(help_text='Sale, Purchase, Expense, etc.', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='outlets.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.bankaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HSNReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('total_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('integrated_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('central_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('state_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cess', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hsn_reports', to='outlets.outlet')),
            ],
            options={
                'unique_together': {('hsn_code', 'month', 'year', 'outlet')},
            },
        ),
        migrations.CreateModel(
            name='GSTReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('GSTR1', 'GSTR-1'), ('GSTR3B', 'GSTR-3B'), ('GSTR9', 'GSTR-9')], max_length=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('b2b_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('b2c_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('export_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('input_tax_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_reports', to='outlets.outlet')),
            ],
            options={
                'unique_together': {('report_type', 'month', 'year', 'outlet')},
            },
        ),
    ]
